Repository stryker-mutator/weapon-regex, pull requests merged in 2023-12, with the labels that each got.

#240 build(deps): update sbt-tpolecat from 0.4.4 to 0.5.0
  build.sbt
  project/plugins.sbt
Labels: dependencies

#250 build(deps): update scala-library from 2.13.11 to 2.13.12
  .github/workflows/docs.yml
  .github/workflows/scala.yml
  build.sbt
Labels: dependencies

#249 Support parsing Unicode Character Class with property and value `\p{property=value}`
  README.md
  core/src/main/scala/weaponregex/model/regextree/predefinedCharClassNode.scala
  core/src/main/scala/weaponregex/mutator/BuiltinMutators.scala
  core/src/main/scala/weaponregex/mutator/predefCharClassMutator.scala
  core/src/main/scala/weaponregex/parser/Parser.scala
  core/src/main/scala/weaponregex/parser/ParserJS.scala
  core/src/test/scala/weaponregex/model/regextree/PredefinedCharClassNodeTest.scala
  core/src/test/scala/weaponregex/mutator/PredefCharClassMutatorTest.scala
  core/src/test/scala/weaponregex/parser/ParserJSTest.scala
  core/src/test/scala/weaponregex/parser/ParserJVMTest.scala
  design/Grammar.ebnf
  docs/README.md
Labels: 🧭 parser

#268 feat: better mutant descriptions
  core/src/main/scala/weaponregex/model/Location.scala
  core/src/main/scala/weaponregex/model/Position.scala
  core/src/main/scala/weaponregex/model/mutation/TokenMutator.scala
  core/src/main/scala/weaponregex/mutator/BuiltinMutators.scala
  core/src/main/scala/weaponregex/mutator/boundaryMutator.scala
  core/src/main/scala/weaponregex/mutator/capturingMutator.scala
  core/src/main/scala/weaponregex/mutator/charClassMutator.scala
  core/src/main/scala/weaponregex/mutator/predefCharClassMutator.scala
  core/src/main/scala/weaponregex/mutator/quantifierMutator.scala
  core/src/main/scalajs/weaponregex/model/mutation/TokenMutatorJS.scala
  core/src/test/scala/weaponregex/model/regextree/RegexTreeTest.scala
  core/src/test/scala/weaponregex/mutator/MutatorTest.scala
  index.d.ts
  node/test/api.js
Labels: ✨ enhancement, 🧬 mutator

#272 chore(main): release 1.2.1
  CHANGELOG.md
Labels: autorelease: pending

#275 chore(main): release 1.3.0
  CHANGELOG.md
Labels: autorelease: pending
